language: php
php:
  - '5.6'
services:
  - mysql
before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
install:
  - apt-get install -y php5.6-cli php5.6-mysql php5.6-curl php5.6-memcached composer zip
script: find . -name "*.php" -print0 |xargs -0 -n1 -P8 php -l
