version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/rs-machine/
permissions:
    - object: /home/ubuntu/rs-machine/
      owner: ubuntu
      group: ubuntu
      mode: 775
      type:
       - directory
hooks:
# BeforeInstall:
#    - location: rs-machine/deploy/predeploy.sh
  AfterInstall:
    - location: rs-machine/deploy/postdeploy.sh
