version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/rs-machine/
file_exists_behavior: OVERWRITE
permissions:
    - object: /home/ubuntu/rs-machine/
      owner: ubuntu
      group: ubuntu
      mode: 775
      type:
       - directory
       - file
       - symlink
hooks:
  BeforeInstall:
    - location: deploy/predeploy.sh
      runas: ubuntu
      timeout: 300
      interpreter: ["/bin/bash", "deploy/predeploy.sh"]
  AfterInstall:
    - location: deploy/postdeploy.sh
      runas: ubuntu
      timeout: 300
      interpreter: ["/bin/bash", "deploy/postdeploy.sh"]
