version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/rs-machine/
permissions:
    - object: /home/ubuntu/rs-machine/
      owner: ubuntu
      group: ubuntu
      mode: 775
      acls:
        - "d:u::rwx"
        - "d:g::rwx"
        - "d:o::rwx"
      type:
       - directory
#hooks:
# BeforeInstall:
#    - location: rs-machine/deploy/predeploy.sh
# AfterInstall:
    - location: rs-machine/deploy/postdeploy.sh
#    - location: php rs-machine/deploy/log_deployment.php
