services:
  machine:
    build: .
    container_name: rs_machine
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: richmondsunlight
      DB_USER: ricsun
      DB_PASS: password
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  db:
    build:
      context: deploy/
      dockerfile: MySQL.Dockerfile
    container_name: rs_machine_db
    volumes:
      - db_data:/var/lib/mariadb/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
